### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by ashishCDN0135** [brucetoo/ListVideoPlay#4]
V/VideoPlayerView@711375492: 4144 setDataSource, path http://cdnsolutionsgroup.com/vinehub//uploads/vines/videos/996e80274d4713c202e7ff549c535f69.mp4, this VideoPlayerView@711375492
05-29 15:35:28.646 13280-13607/com.brucetoo.listvideoplay V/MediaPlayerWrapperImpl@48673234: 4144 setDataSource, filePath http://cdnsolutionsgroup.com/vinehub//uploads/vines/videos/996e80274d4713c202e7ff549c535f69.mp4, mState IDLE
05-29 15:35:28.646 13280-13607/com.brucetoo.listvideoplay D/MediaPlayer: setDataSource IOException happend : 
                                                                         java.io.FileNotFoundException: No content provider: http://cdnsolutionsgroup.com/vinehub//uploads/vines/videos/996e80274d4713c202e7ff549c535f69.mp4
                                                                             at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1074)
                                                                             at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:927)
                                                                             at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:854)
                                                                             at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1085)
                                                                             at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1059)
                                                                             at com.brucetoo.listvideoplay.videomanage.ui.MediaPlayerWrapper.setDataSource(MediaPlayerWrapper.java:129)
                                                                             at com.brucetoo.listvideoplay.videomanage.ui.VideoPlayerView.setDataSource(VideoPlayerView.java:258)
                                                                             at com.brucetoo.listvideoplay.videomanage.playermessages.SetUrlDataSourceMessage.performAction(SetUrlDataSourceMessage.java:25)
                                                                             at com.brucetoo.listvideoplay.videomanage.playermessages.PlayerMessage.runMessage(PlayerMessage.java:41)
                                                                             at com.brucetoo.listvideoplay.videomanage.MessagesHandlerThread$1.run(MessagesHandlerThread.java:64)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:818)
05-29 15:35:28.646 13280-13607/com.brucetoo.listvideoplay D/MediaPlayer: Couldn't open file on client side, trying server side

**Comment by brucetoo** [comment]
You can see [this](https://stackoverflow.com/questions/42106294/android-media-stream-error-java-io-filenotfoundexception-no-content-provider), may help
