### ISSUE TITLE
App crashes when trying to play any video in recyclerview example

### ISSUE THREAD

**Issue by amanzan** [brucetoo/ListVideoPlay#6]
App crashes when trying to play any video in recyclerview example. Could you please take a look at it? It happens cloning the repo and running, without any modification

**Comment by brucetoo** [comment]
please offer some crash log.

**Comment by amanzan** [comment]
```
Process: com.brucetoo.listvideoplay, PID: 19831
                                                                            java.lang.RuntimeException: this should be called in Main Thread
                                                                                at com.brucetoo.listvideoplay.videomanage.ui.MediaPlayerWrapper.onVideoSizeChanged(MediaPlayerWrapper.java:151)
                                                                                at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3289)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by OsBelief** [comment]
类MediaPlayerWrapper判断是否是UI线程的方法inUiThread有误
![image](https://user-images.githubusercontent.com/4343467/38087874-670256d2-338c-11e8-980d-31b34e19307e.png)

**Comment by brucetoo** [comment]
update to the latest code. already fixed(Wrong ui thread judgement)
